apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: totyi5kbz-go
  janus-idp.io/tekton: totyi5kbz-go
  backstage.io/kubernetes-id: totyi5kbz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: totyi5kbz-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
